drop table wish if exists;
drop table oauth_account if exists;
drop table product_option if exists;
drop table product if exists;
drop table member if exists;

create table product
(
    id          bigint generated by default as identity,
    name        varchar(15) not null,
    price       integer not null,
    image_url    varchar(255) not null,
    approved    boolean default true not null,
    description varchar(1024),
    created_at  timestamp not null default now(),
    updated_at  timestamp not null default now(),
    primary key (id)
);

create table member
(
    id          bigint generated by default as identity,
    email       varchar(255) not null unique,
    password    varchar(255) not null,
    role        varchar(50) not null default 'USER',
    primary key (id)
);

create table wish
(
    id         bigint generated by default as identity,
    member_id  bigint not null,
    product_id bigint not null,
    created_at  timestamp not null default now(),
    updated_at  timestamp not null default now(),
    primary key (id)
);

create table product_option
(
    id          bigint generated by default as identity,
    name        varchar(50) not null,
    quantity    bigint not null,
    product_id  bigint not null,
    primary key(id)
);

create table oauth_account
(
    id          bigint generated by default as identity,
    kakao_id    varchar(255) not null unique,
    member_id   bigint not null,
    primary key(id)
);

alter table if exists wish
    add constraint fk_wish_member_id_ref_member_id
    foreign key (member_id)
    references member;

alter table if exists wish
    add constraint fk_wish_product_id_ref_product_id
    foreign key (product_id)
    references product;

alter table if exists product_option
    add constraint fk_product_option_product_id_ref_product_id
    foreign key (product_id)
    references product;

alter table if exists oauth_account
    add constraint fk_oauth_account_member_id_ref_member_id
    foreign key (member_id)
    references member;